name: 💡 Feature request
description: Got a suggestion for a new idea/feature for Ganesh Korada's portfolio?
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
  description: A brief explanation of the feature you want to see in Ganesh Korada's portfolio.
    validations:
      required: true

  - type: textarea
    id: whatsnew
    attributes:
      label: What's new?
  description: If the proposal involves a new component or a redesign of a previous component in Ganesh Korada's portfolio.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
  description: Why should this be added? What use cases does it support? What is the expected outcome for Ganesh Korada's portfolio?
    validations:
      required: true

  - type: textarea
    id: extrainfo
    attributes:
      label: Additional context
  description: Add any other context or screenshots about the feature request for Ganesh Korada's portfolio here.
    validations:
      required: false

